### ISSUE TITLE
passwall安装哪个版本

### ISSUE THREAD

**Issue by jameqq** [xiangfeidexiaohuo/EasyWrt#1]
NX30Pro用哪个版本的passwall

**Comment by xiangfeidexiaohuo** [comment]
> NX30Pro用哪个版本的passwall

如果要用passwall  可以考虑，使用istore装离线应用包passwall。

某些特殊插件的离线包：
https://github.com/AUK9527/Are-u-ok/tree/main/apps


或者 使用大分区固件，带passwall。
