### ISSUE TITLE
跪求大佬添加luci-app-eqosplus 

### ISSUE THREAD

**Issue by leaguetao** [xiangfeidexiaohuo/EasyWrt#11]
大佬下次更新能不能把 https://github.com/sirpdboy/luci-app-eqosplus 这个插件添加进去啊  感谢大佬~

**Comment by leaguetao** [comment]
https://github.com/sirpdboy/sirpdboy-package/tree/main/luci-app-eqosplus  还有这个参考

**Comment by xiangfeidexiaohuo** [comment]
有 网速控制 这个就不加了  简单固件 只是很简单的   不加这些，可以去看看 AE86Wrt 这个项目 ，常规插件都加了
