### ISSUE TITLE
如何解决RAX3000m丢失配置的问题

### ISSUE THREAD

**Issue by tangqiu0205** [xiangfeidexiaohuo/EasyWrt#12]
今天刚刷的这个固件,发现只要重启之前所有配置过的项目全都恢复了默认.
我的路由器是rax3000m  emmc版本.

**Comment by xiangfeidexiaohuo** [comment]
> 今天刚刷的这个固件,发现只要重启之前所有配置过的项目全都恢复了默认. 我的路由器是rax3000m emmc版本.

很迷茫这个机器

**Comment by tangqiu0205** [comment]
难崩，我暂时换其他固件了。

**Comment by slty7** [comment]
意思这个问题解决了
