### ISSUE TITLE
AX3000t 

### ISSUE THREAD

**Issue by rugayen** [xiangfeidexiaohuo/EasyWrt#14]
小米AX3000T的固件有没有支持an8855的交换驱动？？

**Comment by xiangfeidexiaohuo** [comment]
> 小米AX3000T的固件有没有支持an8855的交换驱动？？

这是另外一个版本，要重新整个固件。不能直接刷ax3000t的固件。

**Comment by xiangfeidexiaohuo** [comment]
> > 小米AX3000T的固件有没有支持an8855的交换驱动？？
> 
> 这是另外一个版本，要重新整个固件。不能直接刷ax3000t的固件。

https://github.com/xiangfeidexiaohuo/EasyWrt/issues/14#issuecomment-2501829875

**Comment by xiangfeidexiaohuo** [comment]
> > 小米AX3000T的固件有没有支持an8855的交换驱动？？
> 
> 这是另外一个版本，要重新整个固件。不能直接刷ax3000t的固件。

https://github.com/xiangfeidexiaohuo/EasyWrt/issues/14#issuecomment-2501829875

**Comment by xiangfeidexiaohuo** [comment]
> 小米AX3000T的固件有没有支持an8855的交换驱动？？

releases 里已经有an8855的固件了
