### ISSUE TITLE
如何安装

### ISSUE THREAD

**Issue by bncolin** [xiangfeidexiaohuo/EasyWrt#3]
偶然间看到大神的固件，我对op一知半解，有几个问题咨讯下
1，是否是hanwckf的源码，闭源驱动
2，如果我已经是H大的固件，是否直接在op界面里直接升级就可以，用不着uboot
3，您的固件升级频繁，都有哪些更新？是否每次都要升级

**Comment by xiangfeidexiaohuo** [comment]
> 偶然间看到大神的固件，我对op一知半解，有几个问题咨讯下 1，是否是hanwckf的源码，闭源驱动 2，如果我已经是H大的固件，是否直接在op界面里直接升级就可以，用不着uboot 3，您的固件升级频繁，都有哪些更新？是否每次都要升级

是闭源驱动，如果是H大的 固件，建议首次还是uboot刷入，干净。更新，懒得写日志，无非就是同步H大最新源码，又没啥其他的东西，只是设定了每周更新一次，这种20M的小固件，月更就好。

**Comment by bncolin** [comment]
没理解错的话您的建议是为了纯净最好是uboot.我op下不保留配置直接升级的话，应该也不会导致变砖，应该是这样吧。
关于更新的问题您已经讲的非常清楚了，我懂了
我不会自己编译，一直想找个纯净的固件，需要什么插件自己安装，很期待您的固件，有不明白的再请教，谢谢
