### ISSUE TITLE
RedmiAX6000版本的UU加速器无法使用，会报错

### ISSUE THREAD

**Issue by lvdhuixvan** [xiangfeidexiaohuo/EasyWrt#5]
如题

**Comment by xiangfeidexiaohuo** [comment]
> 如题

报的啥

**Comment by lvdhuixvan** [comment]
> > 如题
> 
> 报的啥

404 未找到
对不起，请求的目标未找到。
No page is registered at '/admin/services'. If this url belongs to an extension, make sure it is properly installed. If the extension was recently installed, try removing the /tmp/luci-indexcache file.
无法调度: /cgi-bin/luci/admin/services/uuplugin

**Comment by xiangfeidexiaohuo** [comment]
> > > 如题
> > 
> > 
> > 报的啥
> 
> 404 未找到 对不起，请求的目标未找到。 No page is registered at '/admin/services'. If this url belongs to an extension, make sure it is properly installed. If the extension was recently installed, try removing the /tmp/luci-indexcache file. 无法调度: /cgi-bin/luci/admin/services/uuplugin

上游商店插件需要更新， 和固件无关，自己单独去找插件安装吧。
