### ISSUE TITLE
首次刷入要求密码

### ISSUE THREAD

**Issue by Kalansas** [xiangfeidexiaohuo/EasyWrt#6]
我的机器是中国移动RAX3000M，刷了大大的固件后进首页发现要密码，用SSH登录也一样，然而我网上看到大大的固件是不需要密码的，请问密码是多少？

**Comment by xiangfeidexiaohuo** [comment]
> 我的机器是中国移动RAX3000M，刷了大大的固件后进首页发现要密码，用SSH登录也一样，然而我网上看到大大的固件是不需要密码的，请问密码是多少？

如果要密码，应该就是默认的 password
