### ISSUE TITLE
能否安装mosdns

### ISSUE THREAD

**Issue by bncolin** [xiangfeidexiaohuo/EasyWrt#7]
在https://github.com/sbwml/luci-app-mosdns 中作者提到“需要 golang 1.20.x 或最新版本（openwrt-21.02 及旧版本需要）”
我不知道您的固件是否是高于这个版本并可以正常安装mosdns

**Comment by xiangfeidexiaohuo** [comment]
> 在https://github.com/sbwml/luci-app-mosdns 中作者提到“需要 golang 1.20.x 或最新版本（openwrt-21.02 及旧版本需要）” 我不知道您的固件是否是高于这个版本并可以正常安装mosdns
现在都是120
