### ISSUE TITLE
rax3000m每次重启配置丢失。

### ISSUE THREAD

**Issue by opplin** [xiangfeidexiaohuo/EasyWrt#8]
rax3000m每次重启配置都丢失，装的软件和配置的密码都没了，像刚刷那样。请问是怎么解决呢？谢谢。

/dev/mmcblk0p5 on /rom type squashfs (ro,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
tmpfs on /tmp/root type tmpfs (rw,noatime,mode=755)
overlayfs:/tmp/root on / type overlay (rw,noatime,lowerdir=/,upperdir=/tmp/root/upper,workdir=/tmp/root/work)
tmpfs on /dev type tmpfs (rw,nosuid,relatime,size=512k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600,ptmxmode=000)
debugfs on /sys/kernel/debug type debugfs (rw,noatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,noatime,mode=700)
pstore on /sys/fs/pstore type pstore (rw,noatime)
mountd(pid4712) on /tmp/run/blockd type autofs (rw,relatime,fd=7,pgrp=4712,timeout=30,minproto=5,maxproto=5,indirect)

**Comment by xiangfeidexiaohuo** [comment]
> rax3000m每次重启配置都丢失，装的软件和配置的密码都没了，像刚刷那样。请问是怎么解决呢？谢谢。
> 
> /dev/mmcblk0p5 on /rom type squashfs (ro,relatime) proc on /proc type proc (rw,nosuid,nodev,noexec,noatime) sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime) cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate) tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime) tmpfs on /tmp/root type tmpfs (rw,noatime,mode=755) overlayfs:/tmp/root on / type overlay (rw,noatime,lowerdir=/,upperdir=/tmp/root/upper,workdir=/tmp/root/work) tmpfs on /dev type tmpfs (rw,nosuid,relatime,size=512k,mode=755) devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600,ptmxmode=000) debugfs on /sys/kernel/debug type debugfs (rw,noatime) none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,noatime,mode=700) pstore on /sys/fs/pstore type pstore (rw,noatime) mountd(pid4712) on /tmp/run/blockd type autofs (rw,relatime,fd=7,pgrp=4712,timeout=30,minproto=5,maxproto=5,indirect)

是不是空间不够哟
