### ISSUE TITLE
希望增加wireguard内核模块或插件

### ISSUE THREAD

**Issue by gunpen** [xiangfeidexiaohuo/EasyWrt#9]
原来一直使用xwrt固件，就是看中它内置了wireguare接口，但是其他方面却远不如EasyWrt，于是刷了本固件，去无法安装wireguard，说是kmod-wireguard，希望大佬能增加上。

**Comment by ldd200888** [comment]
这个21版本的OP好像没有kmod-wireguard。。。我没找见有这个模块

**Comment by ldd200888** [comment]
@gunpen 已添加，这儿下载：https://github.com/ldd200888/EasyWrt/releases/tag/20240613185026
